Repository invertase/notifee, pull requests merged in 2022-04, with the labels that each got.

#332 feat(android): Expose api to handle Android 12 REQUIRE_EXACT_ALARM permission
  android/src/main/AndroidManifest.xml
  android/src/main/java/app/notifee/core/AlarmPermissionBroadcastReceiver.java
  android/src/main/java/app/notifee/core/Notifee.java
  android/src/main/java/app/notifee/core/NotifeeAlarmManager.java
  android/src/main/java/app/notifee/core/utility/AlarmUtils.java
  docs/navigator.json
  docs/react-native/docs/triggers.md
  packages/react-native/android/src/main/java/io/invertase/notifee/NotifeeApiModule.java
  packages/react-native/src/NotifeeApiModule.ts
  packages/react-native/src/__mocks__/NotifeeNativeModule.ts
  packages/react-native/src/types/Module.ts
  packages/react-native/src/types/Notification.ts
  packages/react-native/src/types/NotificationAndroid.ts
  tests_react_native/__tests__/NotifeeApiModule.test.ts
  tests_react_native/android/app/src/androidTest/java/com/invertase/testing/GetNotificationSettingsTest.java
  tests_react_native/example/app.tsx
Labels: enhancement, android, android 12

#371 fix(expo): increase compileSdkVersion to 31 and add EAS instructions to doc
  docs/react-native/docs/installation.md
  packages/react-native/plugin/__tests__/__snapshots__/androidProjectBuild.test.ts.snap
  packages/react-native/plugin/__tests__/__snapshots__/fullPlugin.test.ts.snap
  packages/react-native/plugin/__tests__/androidProjectBuild.test.ts
  packages/react-native/plugin/__tests__/fullPlugin.test.ts
  packages/react-native/plugin/src/withNotifeeProjectGradlePlugin.ts
  tests_react_native/jest.config.js
Labels: pending-merge

#289 fix(android): allow the projects to specify names of their apps
  packages/react-native/android/build.gradle
Labels: do-not-merge

#387 fix(test, jest): changes in release 5.1.0 not reflected in jest-mock
  packages/react-native/jest-mock.js
Labels: pending-merge
